### PR TITLE
Keyboard navigation 

### PR DESCRIPTION
**Pull request by FluencyMatt**
A previous pull request (#23) from @raymondmuller to add keyboard navigation failed merging due reduced unit test coverage, so I beefed it up where it was lacking.

### CODE REVIEW

**Comment by Hawxy** [comment]
@alexurquhart could this be merged?

**Comment by FluencyMatt** [comment]
@alexurquhart is there something we can do to push this through?

**Comment by micon4sure** [comment]
Aww damn. I added keyboard controls too, didn't see this pull request. And it's been here more than 3 months. Save to say this repo is dead?

**Comment by Hawxy** [comment]
I've personally just taken the source and integrated the changes I needed. Also allowed me to remove stuff I don't use and reduce it down to 2 files.

**Comment by mattzollinhofer** [comment]
This PR (and one or two others) is the exact reason I wanted to revive (but ended up having to fork: https://github.com/mattzollinhofer/vue-typeahead-bootstrap) this repository. I really wanted a more accessible tool to use and I saw this (and other) PRs that had already been submitted to solve the problem!

To that end, I merged in functionality that I think meets this need here: mattzollinhofer/vue-typeahead-bootstrap@6646027. This implementation is mildly different but I believe the outcome is essentially the same.

Thanks again and chime in here or on the fork if you have any other thoughts! 😄

You can find the functionality on npm here: https://www.npmjs.com/package/vue-typeahead-bootstrap.

**Pull request closed without merging**
