### PR TITLE
Add support for minMatchingChars=0

### LINKED ISSUE #39: Option: Show all on initial focus event
Is it currently possible to show all on initial focus event? I have tried setting minMatchingChars=0 which will show all after a key is pressed.

### PR DESCRIPTION
**Pull request by jhalag**
Allow displaying the list on initial select if minMatchingChars==0

Resolves #39

### CODE REVIEW

**Comment by isaacmillercodes** [comment]
Any word on when this might be merged in? I could use this for a project I'm working on. Thanks!

**Comment by Lobidu** [comment]
+1

**Comment by jhalag** [comment]
I do not intend to take over maintenance of the project, but if anyone needs a version that has this fix, as well as #32 and #29  merged it is available on my fork. (FYI: there are additional changes present which I have made for my own project's use)

**Comment by jhalag** [comment]
Closing PR, creating new one off correct branch

**Comment by mattzollinhofer** [comment]
If anyone stumbles across this PR. I am attempting to maintain this project, but had to fork it to here: https://github.com/mattzollinhofer/vue-typeahead-bootstrap. 

I merged in functionality that I think meets this need here: https://github.com/mattzollinhofer/vue-typeahead-bootstrap/commit/09a6cf75494f487058bad90701d547bf05d7837a. This implementation refers to it as `showOnFocus` rather than re-using `minMatchingChars` but I believe the outcome is essentially the same unless I'm not understanding.

You can use the functionality under the forked project: https://www.npmjs.com/package/vue-typeahead-bootstrap or https://github.com/mattzollinhofer/vue-typeahead-bootstrap.

Hope this helps anyone who needs this functionality going forward!

**Pull request closed without merging**
